// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ihGpbalYTdbiAEq_8YpGp9Rn7Aqv8SI',
    appId: '1:913529947736:web:5275bfc6f244bc261bac2d',
    messagingSenderId: '913529947736',
    projectId: 'nichrome-connect-11ec9',
    authDomain: 'nichrome-connect-11ec9.firebaseapp.com',
    storageBucket: 'nichrome-connect-11ec9.appspot.com',
    measurementId: 'G-ED2V59E4WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg9vNx8Qzdev0bFxRo6jzQm_5SqRI0db8',
    appId: '1:913529947736:android:a88772936797cf501bac2d',
    messagingSenderId: '913529947736',
    projectId: 'nichrome-connect-11ec9',
    storageBucket: 'nichrome-connect-11ec9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGfK2sE86niKRhCPVbcpYFoPfytJtBpdc',
    appId: '1:913529947736:ios:4fce572885ee77fc1bac2d',
    messagingSenderId: '913529947736',
    projectId: 'nichrome-connect-11ec9',
    storageBucket: 'nichrome-connect-11ec9.appspot.com',
    iosBundleId: 'com.example.nichrome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGfK2sE86niKRhCPVbcpYFoPfytJtBpdc',
    appId: '1:913529947736:ios:4fce572885ee77fc1bac2d',
    messagingSenderId: '913529947736',
    projectId: 'nichrome-connect-11ec9',
    storageBucket: 'nichrome-connect-11ec9.appspot.com',
    iosBundleId: 'com.example.nichrome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9ihGpbalYTdbiAEq_8YpGp9Rn7Aqv8SI',
    appId: '1:913529947736:web:1734580a443667561bac2d',
    messagingSenderId: '913529947736',
    projectId: 'nichrome-connect-11ec9',
    authDomain: 'nichrome-connect-11ec9.firebaseapp.com',
    storageBucket: 'nichrome-connect-11ec9.appspot.com',
    measurementId: 'G-7WZDJ4DGJL',
  );

}